---
version: "3"
services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - ./testdata/testdata/postgres.sql.gz:/docker-entrypoint-initdb.d/postgres.sql.gz
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foxsur
    ports:
      - "5432:5432"